export const MOVIES = {
  MAIN: "GET_MOVIES_MAIN",
  SUCCESS: "GET_MOVIES_SUCCESS",
  FAILURE: "GET_MOVIE_FAILURE",
};

export const MOVIES_SEARCH = {
  MAIN: "MOVIES_SEARCH_MAIN",
  SUCCESS: "MOVIES_SEARCH_SUCCESS",
  FAILURE: "MOVIE_SEARCH_FAILURE",
};
